#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int lightThreshold = 47;
int lineCounter = 0;

void incrementLineCounter()
{
	writeDebugStream("Incrementing Line Counter\n");
	lineCounter++;
	//Main direction logic based on number of lines that we've crossed
	switch (lineCounter)
	{
	case 1:
		writeDebugStream("Case 1\n");
		displayVariableValues(1,lineCounter);
		turnLeft(182, degrees, 25);
		break;
	case 2:
		writeDebugStream("Case 2\n");
		displayVariableValues(1,lineCounter);
		turnRight(182, degrees, 25);
		forward(1, rotations, 25);
		turnRight(182, degrees, 25);
		break;
	case 3:
		writeDebugStream("Case 3\n");
		displayVariableValues(1,lineCounter);
		break;
	case 4:
		writeDebugStream("Case 4\n");
		displayVariableValues(1,lineCounter);
		turnLeft(182, degrees, 25);
		forward(2, rotations, 25);
		turnLeft(182, degrees, 25);
		break;
	case 5:
		displayVariableValues(1,lineCounter);
		break;
	case 6:
		displayVariableValues(1,lineCounter);
		break;
	case 7:
		displayVariableValues(1,lineCounter);
		break;
	case 8:
		displayVariableValues(1,lineCounter);
		break;
	case 9:
		displayVariableValues(1,lineCounter);
		break;
	case 10:
		displayVariableValues(1,lineCounter);
		break;
	default:

		break;
	}

	return;

}

task main()
{
	writeDebugStream("Starting Program\n");
	backward(2, seconds, 25);
	turnRight(190, degrees, 25);
	forward(1, seconds, 25);

	writeDebugStream("This is my debug stream\n");

	//Main while loop
	while(true)
	{

		writeDebugStream("In Main Loop\n");

		//Orient
		while (SensorValue(light) <= lightThreshold)
		{
			forward(5, milliseconds, 25);
			writeDebugStream("Incrementing Forward\n");
		}
		incrementLineCounter();
	}
}
