#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     color,          sensorColorNxtFULL)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, openLoop, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, openLoop, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lightThreshold = 50;

	while (SensorValue(light) > lightThreshold)
	{
		motor[motorC] = 50;
		motor[motorB] = 50;

		if (SensorValue(light) <= lightThreshold)
		{
			backward(1, rotations, 50);
			turnRight(180, degrees, 50);
		}
	}
}
