#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int lightThreshold = 45;
int lineCounter = 0;

task incrementLineCounter()
{
	lineCounter++;
	//Main direction logic based on number of lines that we've crossed
	switch (lineCounter)
	{
	case 1:
		displayVariableValues(1,lineCounter);
		turnLeft(182, degrees, 25);
		break;
	case 2:
		displayVariableValues(1,lineCounter);
		turnRight(182, degrees, 25);
		forward(1, rotations, 25);
		turnRight(182, degrees, 25);
		break;
	case 3:
		displayVariableValues(1,lineCounter);
		break;
	case 4:
		displayVariableValues(1,lineCounter);
		turnLeft(182, degrees, 25);
		forward(2, rotations, 25);
		turnLeft(182, degrees, 25);
		break;
	case 5:
		displayVariableValues(1,lineCounter);
		break;
	case 6:
		displayVariableValues(1,lineCounter);
		break;
	case 7:
		displayVariableValues(1,lineCounter);
		break;
	case 8:
		displayVariableValues(1,lineCounter);
		break;
	case 9:
		displayVariableValues(1,lineCounter);
		break;
	case 10:
		displayVariableValues(1,lineCounter);
		break;
	default:

		break;
	}

}

task main()
{
	backward(2, seconds, 25);
	turnRight(190, degrees, 25);
	forward(1, seconds, 25);

	do
	{
		forward(5, milliseconds, 25);
		if (SensorValue(light) <= lightThreshold)
		{
			startTask(incrementLineCounter);
		}
		if (SensorValue(touch) >= 1)
		{
			backward(1, rotations, 25)	;
		}

	}while (lineCounter < 11);
}
