#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int lightThreshold = 45;
int lineCounter = 0;

task incrementLineCounter(){
}


task main()
{
	//backward(2, seconds, 25);
	turnRight(182, degrees, 25);
	forward(3.5, seconds, 50);

	turnLeft(175, degrees, 25);
	forward(4, seconds, 100);

	turnRight(180, degrees, 25);
	forward(1.5, seconds, 100);
	turnRight(200, degrees, 25);

	forward(4.5, seconds, 100);

	turnLeft(192, degrees, 25);
	forward(2.3, seconds, 100);
	turnLeft(170, degrees, 25);

	forward(8, seconds, 100);

	turnRight(190, degrees, 25);
	forward(3, seconds, 50);
	turnRight(180, degrees, 25);

	forward(2.5, seconds, 100);
	turnLeft(182, degrees, 25);
	forward(2, seconds, 100);
	turnLeft(182, degrees, 25);
	forward(3, seconds, 100);


	/*while(SensorValue(light) < 90){
		motor[motorB] = 100;
	}*/

/*	while(SensorValue(touch)==0){
		forward();
	}

	turnRight(182, degrees, 25);

	while(SensorValue(touch) == 0){
		forward();
	}
*/

}
