#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
static int HAS_STARTED = 0;
static int HAS_NOT_STARTED = 1;
static int ORIENTED = 0;
static int NOT_ORIENTED = 1;
static int NO_LINE = 0;
static int HAS_LINE = 1;
static int HAS_WALL = 0;
static int NO_WALL = 1;
static int HAS_OBSTACLE = 0;
static int NO_OBSTACLE = 1;

int currentLine = 0;
int lightThreshold = 47;


void exitStartBlock() {
	// backup 1 sec at 50%
	backward(1, seconds, 50);
	// turn right
	turnRight(182, degrees, 50);
	// move forward 2.5 sec at 50%
	forward(2.5, seconds, 50);
	// turn left 90 degress
	turnLeft(182, degrees, 50);
	forward(2, seconds, 100);
}

void lineLogic() {
	switch (currentLine)
	{
	case 1:
		writeDebugStream("Case 1\n");
		displayVariableValues(1,currentLine);
		turnLeft(182, degrees, 25);
		break;
	case 2:
		writeDebugStream("Case 2\n");
		displayVariableValues(1,currentLine);
		turnRight(182, degrees, 25);
		forward(1, rotations, 25);
		turnRight(182, degrees, 25);
		break;
	case 3:
		writeDebugStream("Case 3\n");
		displayVariableValues(1,currentLine);
		break;
	case 4:
		writeDebugStream("Case 4\n");
		displayVariableValues(1,currentLine);
		turnLeft(182, degrees, 25);
		forward(2, rotations, 25);
		turnLeft(182, degrees, 25);
		break;
	case 5:
		displayVariableValues(1,currentLine);
		break;
	case 6:
		displayVariableValues(1,currentLine);
		break;
	case 7:
		displayVariableValues(1,currentLine);
		break;
	case 8:
		displayVariableValues(1,currentLine);
		break;
	case 9:
		displayVariableValues(1,currentLine);
		break;
	case 10:
		displayVariableValues(1,currentLine);
		break;
	default:

		break;
	}
}

void straighten() {
	short sensorDistanceLeft = 0;
	short sensorDistanceRight = 0;

	stopAllMotors();
	forward(200, milliseconds, 100);
	turnLeft(60, degrees, 50);
	sensorDistanceLeft = SensorValue(sonar);
	turnRight(120, degrees, 50);
	sensorDistanceRight = SensorValue(sonar);
	turnLeft(60, degrees, 50);
	if (sensorDistanceLeft >= sensorDistanceRight) {
		turnRight(10, degrees, 50);
	}
	else
	{
		turnLeft(10, degrees, 50);
	}
}

task main()
{
	int orientFlag = NOT_ORIENTED, obstacleFlag = NO_OBSTACLE, wallFlag =  NO_WALL, blacklineFlag = NO_LINE;
	int startFlag = HAS_NOT_STARTED;
	int repCount = 0;

	while(1)
	{
		//orient
		while(orientFlag)
		{
			stopAllMotors();
			if(startFlag)
			{
				exitStartBlock();
				stopAllMotors();
				startFlag = HAS_STARTED;
			}
			else if(obstacleFlag)
			{
				// handle obstacle reorient
				obstacleFlag = 0;
			}
			else if(wallFlag)
			{
				// handle wall reorient
				wallFlag = 0;
			}
			else if(blacklineFlag)
			{
				lineLogic();
			}
			else
			{
				orientFlag = ORIENTED;
				break;
			}
		}


		if(blacklineFlag)
		{
			// cross the line
			forward(250, milliseconds, 100);
			stopAllMotors();
			// set orientFlag
			orientFlag = NOT_ORIENTED;
			// continue
			continue;
		}
		// movement
		forward(20, milliseconds, 50);
		if (SensorValue(light) <= lightThreshold)
		{
			blacklineFlag = HAS_LINE;
			obstacleFlag = HAS_OBSTACLE;
			continue;
		}
		if (repCount >= 10) {
			stopAllMotors();
			straighten();
			repCount = 0;
			} else {
			repCount++;
		}
		stopAllMotors();
	}
}
