#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int lightThreshold = 40;
int lineCounter = 0;

task main()
{
	int orientFlag, obstacleFlag, wallFlag, startFlag, blacklineFlag;
	while(1)
	{
		//orient
		while(orientFlag)
		{
			orienting = 1;
			if(startFlag)
			{
				// handle start reorient
				startFlag = 0;
			}
			else if(obstacleFlag)
			{
				// handle obstacle reorient
				obstacleFlag = 0;
			}
			else if(wallFlag)
			{
				// handle wall reorient
				wallFlag = 0;
			}
			else if(blacklineFlag)
			{
			}
			else
			{
				orientFlag = 0;
			}
		}


		if(blacklineFlag)
		{
			// cross the line
			// set orientFlag
			// continue
		}
		// check sensors and set flags
		// move forward for x amount of time
	}
}
